name: cypress-ci.yml
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  docker-included:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, firefox]
    container:
      image: cypress/included:15.18.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: cypress-io/github-action@v7
        with:
          working-directory: .
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_INSTALL_BINARY: 0
