name: cypress-ci.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker-included:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, firefox]
    container:
      image: cypress/included:15.18.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: cypress-io/github-action@v7
        with:
          working-directory: .
          browser: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: |
            cypress/screenshots
            cypress/videos
        env:
          CYPRESS_INSTALL_BINARY: 0
